#ifndef AOFLAGGER_VERSION_H
#define AOFLAGGER_VERSION_H

#define AOFLAGGER_VERSION_STR      "2.13.2"
#define AOFLAGGER_VERSION_MAJOR    2
#define AOFLAGGER_VERSION_MINOR    13
#define AOFLAGGER_VERSION_SUBMINOR 2
#define AOFLAGGER_VERSION_DATE_STR "2018-12-03"

#endif
